builders:
  imagesBuilder:
    import: "package:flutter_res/builder/res_builder.dart"
    builder_factories: ["imagesBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    build_to: source

